In [13]:
import pandas as pd

#df = pd.read_csv('../../../results/gridsearch/EURUSD/mse_var_grid_1_best_hyp.csv')
df = pd.read_csv('../../../results/gridsearch/EURUSD/best_test_11_02_26_idd_rff.csv')
df.groupby("model").mean()

,fold,L,W,sigma,D,mse,var,us_rff,us_update,s_rff,s_update
model,,,,,,,,,,,
ABO,2.0,20.0,21.0,8.0,8192.0,1.238643,1082.432730,3567.992,6841.6860,6.672146,12.793926
KRLS-RBF,2.0,20.0,421.0,3.1,0.0,1.235124,1085.268796,0.000,7725.9400,0.000000,14.447476
QRD-RLS,2.0,20.0,272.0,NaN,0.0,2.049598,2013.096596,0.000,59.9455,0.000000,0.112098

In [11]:
import pandas as pd

df = pd.read_csv('../../../results/gridsearch/EURUSD/best_test_11_02_26_idd_rff_log11.csv')
df.groupby("model").mean()

,fold,L,W,sigma,D,mse,var,us_rff,us_update,s_rff,s_update
model,,,,,,,,,,,
ABO,2.0,20.0,21.0,8.0,2048.0,1.249864,1088.950272,834.7034,1752.54800,1.560894,3.277264
KRLS-RBF,2.0,20.0,421.0,3.1,0.0,1.235124,1085.268796,0.0000,5632.65800,0.000000,10.533082
QRD-RLS,2.0,20.0,272.0,NaN,0.0,2.049598,2013.096596,0.0000,58.34516,0.000000,0.109106

In [9]:
import pandas as pd

#df = pd.read_csv('../../../results/gridsearch/EURUSD/mse_var_grid_1_best_hyp.csv')
df = pd.read_csv('../../../results/gridsearch/EURUSD/best_test_11_02_26_idd_rff.csv')
df.groupby("model").mean()

,fold,L,W,sigma,D,mse,var,us_rff,us_update,s_rff,s_update
model,,,,,,,,,,,
ABO,2.0,20.0,21.0,8.0,8192.0,1.238643,1082.432730,3512.188,5341.50200,6.567792,9.988602
KRLS-RBF,2.0,20.0,421.0,3.1,0.0,1.235124,1085.268796,0.000,4796.97200,0.000000,8.970340
QRD-RLS,2.0,20.0,272.0,NaN,0.0,2.049598,2013.096596,0.000,60.77828,0.000000,0.113655

In [10]:
import pandas as pd

#df = pd.read_csv('../../../results/gridsearch/EURUSD/mse_var_grid_1_best_hyp.csv')
df = pd.read_csv('../../../results/gridsearch/EURUSD/best_test_11_02_26_idd_rff.csv')
df.groupby("model").mean()

,fold,L,W,sigma,D,mse,var,us_rff,us_update,s_rff,s_update
model,,,,,,,,,,,
ABO,2.0,20.0,21.0,8.0,8192.0,1.238643,1082.432730,3567.992,6841.6860,6.672146,12.793926
KRLS-RBF,2.0,20.0,421.0,3.1,0.0,1.235124,1085.268796,0.000,7725.9400,0.000000,14.447476
QRD-RLS,2.0,20.0,272.0,NaN,0.0,2.049598,2013.096596,0.000,59.9455,0.000000,0.112098

In [4]:
import pandas as pd

#df = pd.read_csv('../../../results/gridsearch/EURUSD/mse_var_grid_1_best_hyp.csv')
df = pd.read_csv('../../../results/gridsearch/EURUSD/best_test_orth_rff.csv')
df.groupby("model").mean()

,fold,L,W,sigma,D,mse,var,us_rff,us_update,s_rff,s_update
model,,,,,,,,,,,
ABO,2.0,20.0,21.0,8.0,8192.0,1.238852,1083.968408,4146.732,10991.51000,7.754388,20.554180
KRLS-RBF,2.0,20.0,421.0,3.1,0.0,1.235124,1085.268796,0.000,6989.13400,0.000000,13.069680
QRD-RLS,2.0,20.0,272.0,NaN,0.0,2.049598,2013.096596,0.000,65.34608,0.000000,0.122197

In [2]:
df

,fold,model,L,W,sigma,D,mse,var,us_rff,us_update,s_rff,s_update
0,0,ABO,20,21,8.0,8192,1.078000,36.40650,3570.98,10958.2000,6.67774,20.491800
1,0,QRD-RLS,20,272,NaN,0,1.253920,39.32830,0.00,68.7121,0.00000,0.128492
2,0,KRLS-RBF,20,421,3.1,0,1.079740,37.35360,0.00,7991.4300,0.00000,14.944000
3,1,ABO,20,21,8.0,8192,1.398150,384.82600,4515.11,18524.0000,8.44326,34.639800
4,1,QRD-RLS,20,272,NaN,0,1.684980,412.39000,0.00,68.1526,0.00000,0.127445
5,1,KRLS-RBF,20,421,3.1,0,1.389750,385.51300,0.00,10850.9000,0.00000,20.291200
6,2,ABO,20,21,8.0,8192,2.535410,4904.31000,4317.67,14510.0000,8.07404,27.133800
7,2,QRD-RLS,20,272,NaN,0,5.945020,9523.25000,0.00,73.5077,0.00000,0.137459
8,2,KRLS-RBF,20,421,3.1,0,2.528950,4916.98000,0.00,7985.5200,0.00000,14.932900
9,3,ABO,20,21,8.0,8192,0.440066,1.56875,4069.60,7400.9100,7.61015,13.839700
10,3,QRD-RLS,20,272,NaN,0,0.476283,1.73998,0.00,70.1728,0.00000,0.131223
11,3,KRLS-RBF,20,421,3.1,0,0.437865,1.54528,0.00,5786.3100,0.00000,10.820400
12,4,ABO,20,21,8.0,8192,0.741587,85.05240,4116.61,7148.0800,7.69806,13.366900
13,4,QRD-RLS,20,272,NaN,0,0.887785,88.77470,0.00,66.2959,0.00000,0.123973
14,4,KRLS-RBF,20,421,3.1,0,0.739315,84.95210,0.00,9040.8300,0.00000,16.906400

In [20]:
summary = df.agg("mean")
summary

TypeError: Could not convert ['ABOQRD-RLSKRLS-RBFABOQRD-RLSKRLS-RBFABOQRD-RLSKRLS-RBFABOQRD-RLSKRLS-RBFABOQRD-RLSKRLS-RBF'] to numeric

In [4]:
g_abo = (
    df.groupby(["L", "W"], as_index=False)
      .agg(
          mse_mean=("mse_abo", "mean"),
          var_mean=("var_abo", "mean")
      )
)
best_abo_mse = g_abo.loc[g_abo["mse_mean"].idxmin()]
best_abo_mse

L           30.000000
W           90.000000
mse_mean     1.018129
var_mean    10.630450
Name: 0, dtype: float64