In [1]:
import pandas as pd

# Read with semicolon delimiter
df_nov = pd.concat([pd.read_csv('../../data/EURUSD/EUR-USD_Minute_2025-11-2'+str(i)+'_UTC.csv', index_col=0) for i in range(4,9)])
df_dic_1 = pd.concat([pd.read_csv('../../data/EURUSD/EUR-USD_Minute_2025-12-0'+str(i)+'_UTC.csv', index_col=0) for i in range(1,5)])
df_dic_2 = pd.concat([pd.read_csv('../../data/EURUSD/EUR-USD_Minute_2025-12-0'+str(i)+'_UTC.csv', index_col=0) for i in range(8,10)])
df_dic_3 = pd.concat([pd.read_csv('../../data/EURUSD/EUR-USD_Minute_2025-12-'+str(i)+'_UTC.csv', index_col=0) for i in range(10,13)])
df_dic_4 = pd.concat([pd.read_csv('../../data/EURUSD/EUR-USD_Minute_2025-12-'+str(i)+'_UTC.csv', index_col=0) for i in range(15,32)])
df_dic_5 = pd.concat([pd.read_csv('../../data/EURUSD/EUR-USD_Minute_2026-01-0'+str(i)+'_UTC.csv', index_col=0) for i in range(1,6)])

/tmp/ipykernel_98419/2527462073.py:8: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_dic_4 = pd.concat([pd.read_csv('../../data/EURUSD/EUR-USD_Minute_2025-12-'+str(i)+'_UTC.csv', index_col=0) for i in range(15,32)])
/tmp/ipykernel_98419/2527462073.py:9: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_dic_5 = pd.concat([pd.read_csv('../../data/EURUSD/EUR-USD_Minute_2026-01-0'+str(i)+'_UTC.csv', index_col=0) for i in range(1,6)])

In [2]:
df_dic_4

                                Open     High      Low    Close  Volume
UTC
15.12.2025 12:00:00.000 UTC  1.17486  1.17498  1.17483  1.17498   57.40
15.12.2025 12:01:00.000 UTC  1.17500  1.17500  1.17493  1.17494   39.42
15.12.2025 12:02:00.000 UTC  1.17495  1.17505  1.17491  1.17496   65.61
15.12.2025 12:03:00.000 UTC  1.17496  1.17496  1.17493  1.17496   50.62
15.12.2025 12:04:00.000 UTC  1.17496  1.17497  1.17489  1.17496   67.61
...                              ...      ...      ...      ...     ...
31.12.2025 21:54:00.000 UTC  1.17458  1.17460  1.17456  1.17457   31.50
31.12.2025 21:55:00.000 UTC  1.17460  1.17464  1.17456  1.17459   21.60
31.12.2025 21:56:00.000 UTC  1.17459  1.17459  1.17457  1.17458    4.50
31.12.2025 21:57:00.000 UTC  1.17459  1.17459  1.17455  1.17455    9.00
31.12.2025 21:58:00.000 UTC  1.17455  1.17457  1.17455  1.17455   38.25

[7055 rows x 5 columns]

In [12]:
all_df = pd.concat([df_nov,df_dic_1,df_dic_2,df_dic_3,df_dic_4,df_dic_5])

In [13]:
import numpy as np

all_x = all_df["Close"].values.reshape(-1,1)
log_ret = np.log(all_x[1:] / all_x[:-1])
log_ret = log_ret.reshape(-1,1)

In [14]:
log_ret.shape

(19087, 1)

In [15]:

def standarize(exog):
    norm_exog = np.zeros((1,exog.shape[1]-1))
    mean_st = []
    std_st = []
    for i in range(2,exog.shape[1]):
        norm_exog[0,i-2] = (exog[0,i-1] - exog[0,:i].mean())/exog[0,:i].std()
        mean_st.append(exog[0,:i].mean())
        std_st.append(exog[0,:i].std())
    
    return norm_exog.T,mean_st,std_st


norm_exog,mean_st,std_st =  standarize(log_ret.T)
tol = 2.22e-16
norm_exog[np.abs(norm_exog) < tol] = 0.0

In [16]:
df_lags = pd.DataFrame(norm_exog)
df_lags.to_csv("../../data/EURUSD/raw_norm_EURUSD.csv", index=False)

In [17]:
lag_matrix = lambda x,lag: np.array([[x[j+i, 0] for j in range(lag)] for i in range(x.shape[0]-lag)])
lags = 25
df_lag_m = lag_matrix(norm_exog, lags)
target_t_0 = norm_exog[lags:]

In [18]:
df_lag_m.shape

(19061, 25)

In [19]:
df_lag_m.shape

(19061, 25)

In [20]:
df_lags

              0
0      1.000000
1      0.941544
2      0.237551
3     -1.276159
4     -1.384269
...         ...
19081  0.412575
19082  0.412541
19083  0.272938
19084 -0.355169
19085  0.000000

[19086 rows x 1 columns]

In [11]:
df_lags = pd.DataFrame(df_lag_m)
df_lags.to_csv("../../data/EURUSD/lags_EURUSD.csv", index=False)

df_target = pd.DataFrame(target_t_0)
df_target.to_csv("../../data/EURUSD/target_EURUSD.csv", index=False)

In [13]:
df_target

              0
0      0.802510
1      0.346278
2      0.227953
3      2.006766
4     -0.286737
...         ...
12588 -0.228724
12589 -0.155967
12590 -0.301478
12591  0.207855
12592  0.000000

[12593 rows x 1 columns]